# Please adjust to your needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y docker.io
    command: docker-compose up

ports:
  - 8888

vscode:
  extensions:
    - ms-python.python
    - dbaeumer.vscode-eslint
